import type { DirectionConfig } from "../types/direction";

export const ANALYST_DIRECTIONS = [
  "Business & Operations",
  "Data & BI",
  "Technical Analyst",
  "Consulting & Strategy",
] as const;

export const DIRECTION_CONFIG = {
  "Business & Operations": {
    title: "Business & Operations",
    description: "Process improvement, stakeholder management and execution.",
    types: [
      "Business Case",
      "Data Interpretation",
      "Guesstimate",
      "Technical",
      "Fit & Behavioural",
    ],
    subjects: {
      "Business Analysis": {
        label: "Business Analysis",
        topics: [
          "Requirements Gathering",
          "Stakeholder Management",
          "Process Mapping",
          "Root Cause Analysis",
          "BRD/FRD Basics",
          "Gap Analysis",
          "UAT Basics",
          "Agile & Scrum Basics",
        ],
      },
      Operations: {
        label: "Operations",
        topics: [
          "Process Improvement",
          "Bottleneck Analysis",
          "SLA & TAT",
          "Capacity & Utilisation",
          "Supply & Demand",
          "Quality & Errors",
          "Operational Efficiency",
          "Customer Experience",
        ],
      },
      "Business Metrics": {
        label: "Business Metrics",
        topics: [
          "Revenue & Profit",
          "Margins",
          "Growth Rates",
          "Conversion Funnel",
          "Retention & Churn",
          "CAC & LTV",
          "Unit Economics",
          "KPIs",
        ],
      },
      Excel: {
        label: "Excel",
        topics: [
          "Excel Fundamentals",
          "Formulas & Conditional Logic",
          "Lookups",
          "Pivot Tables",
          "Data Cleaning",
          "Charts & Reporting",
          "Analysis & Insights",
          "Integrated Excel Case Studies",
        ],
      },
      SQL: {
        label: "SQL",
        topics: [
          "SQL Basics",
          "Filtering",
          "Joins",
          "Aggregation",
          "GROUP BY & HAVING",
          "Subqueries",
          "CTEs",
          "Window Functions Basics",
        ],
      },
      "Data Interpretation": {
        label: "Data Interpretation",
        topics: [
          "Tables",
          "Charts & Graphs",
          "Trends",
          "Percentages & Ratios",
          "Growth Analysis",
          "Comparisons",
          "Outliers",
          "Business Insights",
        ],
      },
      "Business Problem Solving": {
        label: "Business Problem Solving",
        topics: [
          "Root Cause Analysis",
          "Profitability",
          "Growth",
          "Pricing",
          "Market Sizing",
          "Cost Reduction",
          "Process Improvement",
          "Customer Funnel",
        ],
      },
    },
  },
  "Data & BI": {
    title: "Data & BI",
    description: "SQL, dashboards, business metrics and data-driven insights.",
    types: [
      "Technical",
      "Data Interpretation",
      "Case Study",
      "Fit & Behavioural",
    ],
    subjects: {
      SQL: {
        label: "SQL",
        topics: [
          "SQL Basics",
          "Filtering",
          "Joins",
          "Aggregation",
          "GROUP BY & HAVING",
          "Subqueries",
          "CTEs",
          "Window Functions",
          "Date & String Functions",
          "Set Operations",
          "Indexes & Performance Basics",
        ],
      },
      Excel: {
        label: "Excel",
        topics: [
          "Formulas & Functions",
          "Lookups",
          "Pivot Tables",
          "Conditional Logic",
          "Data Cleaning",
          "Charts",
          "What-If Analysis",
          "Power Query Basics",
          "Excel Case Studies",
        ],
      },
      "Python & Pandas": {
        label: "Python & Pandas",
        topics: [
          "Python Basics",
          "DataFrames & Series",
          "Filtering",
          "GroupBy",
          "Merge & Join",
          "Missing Values",
          "Pandas Data Cleaning",
          "NumPy Basics",
          "Vectorisation",
          "EDA",
          "Visualisation Basics",
        ],
      },
      "Power BI & Tableau": {
        label: "Power BI & Tableau",
        topics: [
          "Dashboard Fundamentals",
          "Data Modelling (Relationships & Schema)",
          "Power Query",
          "DAX Basics",
          "Calculated Columns vs Measures",
          "Filters & Slicers",
          "Dashboard Design",
          "Tableau Basics",
        ],
      },
      Statistics: {
        label: "Statistics",
        topics: [
          "Mean/Median/Mode",
          "Variance & Std Dev",
          "Percentiles",
          "Probability Basics",
          "Distributions",
          "Correlation",
          "Hypothesis Testing",
          "Confidence Intervals",
          "A/B Testing",
          "Sampling & Bias",
          "Outliers",
        ],
      },
      "Data Visualisation": {
        label: "Data Visualisation",
        topics: [
          "Chart Selection",
          "Bar/Line/Scatter",
          "Histograms",
          "Visual Hierarchy",
          "Misleading Charts",
          "Common Chart Mistakes",
          "Storytelling with Data",
          "Dashboard Design",
        ],
      },
      "Analytics & Metrics": {
        label: "Analytics & Metrics",
        topics: [
          "KPIs",
          "Revenue & Growth",
          "Conversion Funnel",
          "Retention",
          "Churn",
          "CAC & LTV",
          "Cohort Analysis",
          "Segmentation",
          "Unit Economics",
          "Trend Analysis",
          "Experiment/A-B Testing Metrics",
        ],
      },
      "Product Analytics": {
        label: "Product Analytics",
        topics: [
          "Product Metrics",
          "Acquisition & Activation",
          "Conversion Funnels",
          "Engagement",
          "Retention & Churn",
          "Cohort Analysis",
          "Segmentation",
          "North Star Metrics",
          "A/B Testing & Experiments",
          "Feature Performance",
        ],
      },
    },
  },
  "Technical Analyst": {
    title: "Technical Analyst",
    description:
      "Technical architecture, databases, problem solving and systems.",
    types: [
      "Coding",
      "Technical",
      "Data Interpretation",
      "Case Study",
      "Fit & Behavioural",
    ],
    subjects: {
      SQL: {
        label: "SQL",
        topics: [
          "SQL Basics",
          "Filtering",
          "Joins",
          "Aggregation",
          "CTEs",
          "Subqueries",
          "Window Functions",
          "Query Performance Basics",
        ],
      },
      Python: {
        label: "Python",
        topics: [
          "Python Basics",
          "Data Types",
          "Lists, Tuples, Dicts & Sets",
          "Functions",
          "Classes & OOP in Python",
          "Exceptions",
          "File I/O",
          "Scripting",
        ],
      },
      Excel: {
        label: "Excel",
        topics: [
          "Formulas",
          "Lookups",
          "Pivot Tables",
          "Conditional Functions",
          "Data Cleaning",
          "Charts",
        ],
      },
      "Pandas & NumPy": {
        label: "Pandas & NumPy",
        topics: [
          "DataFrames",
          "Filtering",
          "GroupBy",
          "Merge & Join",
          "Missing Values",
          "Data Cleaning",
          "NumPy Basics",
          "Vectorization",
        ],
      },
      "DSA Basics": {
        label: "DSA Basics",
        topics: [
          "Complexity",
          "Arrays",
          "Strings",
          "Hashing",
          "Stacks & Queues",
          "Searching & Sorting",
          "Recursion Basics",
        ],
      },
      "CS Fundamentals": {
        label: "CS Fundamentals",
        topics: [
          "DBMS",
          "OOP Concepts",
          "Operating Systems",
          "Computer Networks",
          "System Design Basics",
        ],
      },
      "AI & Agentic AI": {
        label: "AI & Agentic AI",
        topics: [
          "AI Fundamentals",
          "GenAI & LLMs",
          "Prompting",
          "RAG",
          "Embeddings & Vector Databases",
          "Agentic AI Basics",
          "AI Agent Workflows",
          "Tool / Function Calling",
          "Hallucinations & Guardrails",
        ],
      },
      "Cloud & APIs": {
        label: "Cloud & APIs",
        topics: [
          "Cloud Fundamentals",
          "IaaS / PaaS / SaaS",
          "AWS / Azure / GCP Basics",
          "Common Cloud Services",
          "REST API Basics",
          "API Integration",
          "Deployment Basics",
        ],
      },
    },
  },
  "Consulting & Strategy": {
    title: "Consulting & Strategy",
    description: "Cases, numbers, recommendations and fit interviews.",
    types: [
      "Case Study",
      "Guesstimate",
      "Data Interpretation",
      "Business / Strategy",
      "Fit & Behavioural",
    ],
    subjects: {
      "Case Interviews": {
        label: "Case Interviews",
        topics: [
          "Profitability",
          "Root Cause Analysis",
          "Revenue Growth",
          "Cost Reduction",
          "Pricing",
          "Market Entry",
          "Operations Improvement",
          "Customer Experience",
          "Capacity & Utilisation",
        ],
      },
      "Business Strategy": {
        label: "Business Strategy",
        topics: [
          "Business Models",
          "Competitive Advantage",
          "Strategic Trade-offs",
          "SWOT Basics",
          "Porter’s Five Forces Basics",
          "Growth Options",
          "Cost vs Differentiation",
          "Partnerships",
          "M&A Basics",
        ],
      },
      "Market & Growth": {
        label: "Market & Growth",
        topics: [
          "Market Entry",
          "Market Expansion",
          "Customer Segmentation",
          "Growth Levers",
          "Pricing Strategy",
          "Go-to-Market Basics",
          "Competitive Analysis",
          "Customer Acquisition",
          "Retention Strategy",
        ],
      },
      Guesstimates: {
        label: "Guesstimates",
        topics: [
          "Population-Based Estimates",
          "Demand Estimation",
          "Capacity Estimation",
          "Revenue Estimation",
          "Market Sizing",
          "Assumption Building",
          "Top-Down vs Bottom-Up",
          "Sanity Checks",
        ],
      },
      "Data Interpretation": {
        label: "Data Interpretation",
        topics: [
          "Tables & Exhibits",
          "Charts & Graphs",
          "Percentages & Ratios",
          "Growth Rates",
          "Profitability Data",
          "Market Share",
          "Trend Analysis",
          "Comparing Alternatives",
          "Business Insights",
        ],
      },
      "Product & Growth Strategy": {
        label: "Product & Growth Strategy",
        topics: [
          "Product Sense",
          "User Problems",
          "Feature Prioritisation",
          "Product Metrics",
          "Acquisition & Activation",
          "Engagement & Retention",
          "North Star Metrics",
          "Monetisation & Pricing",
          "Feature Evaluation",
          "Experimentation Basics",
        ],
      },
      "Fit & Behavioural": {
        label: "Fit & Behavioural",
        topics: [
          "Why Consulting",
          "Tell Me About Yourself",
          "Leadership",
          "Teamwork",
          "Conflict",
          "Failure & Learning",
          "Stakeholder Management",
          "Problem Solving Stories",
          "Communication",
          "Resume / Project Discussion",
        ],
      },
    },
  },
} as const satisfies Record<
  (typeof ANALYST_DIRECTIONS)[number],
  DirectionConfig
>;
